module AbsTree where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Treebank =
   GB [AnnotGTree]
  deriving (Eq,Ord,Show)

data AnnotGTree =
   AG GAnnot GTree
  deriving (Eq,Ord,Show)

data GAnnot =
   GAPlus
 | GAStar
 | GAHash
  deriving (Eq,Ord,Show)

data GTree =
   GTApp GAtom [GTree]
 | GTAtom GAtom
  deriving (Eq,Ord,Show)

data GAtom =
   GFun Ident
 | GMeta
 | GStr String
  deriving (Eq,Ord,Show)

